//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.23 at 02:35:35 AM TRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://flightprovider.com/wsdl", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.flightprovider.wsdl;
